### ISSUE TITLE
Improve exception information display in case of exception in registrations in bootrsrapper class

### ISSUE THREAD

**Issue by i4004** [i4004/AcspNet#205]
Handle bootstrapper exception and Show LoaderExceptions information on AcspOwinMiddleware.OnException

**Comment by asadcs** [comment]
Good Effort boy , I am really impressed by your work , I am working on a project using your ACSP.Net Framework and I have  developed a complete Database application using oyur Library with CRUDE Operation , I want to know that , how can I sue Crystal reports in ACSP.Net , and secondly , It will be appreciated if you provide an example of using multiple buttons on a single form 

Thank you

**Comment by i4004** [comment]
Hello! Sorry, but I don't know how to use Crystal reports, because i am not using it.

Multiple buttons on a single form is not depend on ACSP.NET (server side processing), because it is just HTML (client side) and depend only on HTML specifications, so you can create any number of buttons in a form. :)

**Comment by asadcs** [comment]
Thank you for your Kind and Quick reply , I want to ask that if there are three html buttons on a single Template i.e  one is for create and one is for delete and one is for update , I  have three separate controllers for Delete , Update and Create , with Attribute [Post("CreateDevice")] ,  [Post("DeleteDevice/{IPAddress}/{MacAddress}/{ComportNumber}")]  and  [Post("UpdateDevice/{IPAddress}/{MacAddress}/{ComportNumber}")] and with 3 different templates and views , i.e create.tpl, delete.tpl and update.tpl , single button on each page , button is automatically calling the controller , is there any way , I can define the redirect path with button in the code , i.e. if I design a single template  and which contains 3 html buttons , now how will ACSP.Net will decide that which button is calling which controller , can you please upload an example of 2 buttons on one template file calling two different controllers with POST attributes .Thank you very much

**Comment by asadcs** [comment]
is there any other way of integrate reporting > other than crystal reports . I also want to be the contributor of your project , Can I become contributor ?

**Comment by i4004** [comment]
Yes, you can become a contributor, any pull requests are welcome :)

I not tried any "Reporting" tools with ACSP.NET, but techinally report can be just a HTML page, for example, with table on it :)

Can you show me some of your code of delete.tpl/update.tpl?

**Comment by asadcs** [comment]
yes Sure , how can I send you the Code , whats your email ID ? Secondly there is another bug in publishing the website .When ever we publish website ,  we have to copy two folders manually 1)-Templates Folder and 2)-App_Data Folder

**Comment by i4004** [comment]
Can you put it here?
You should set build type "content" in file properties on each file in App_Data and Templates folder in solution explorer.

**Comment by asadcs** [comment]
yes sure

**Comment by asadcs** [comment]
i really dont know how to use git hub as i am new here , right now i am in my office and we are not allowed to upload any thing from here , I will send you the code from my home , it will be appropriate if you give me email address so that i can provide you the drop box link .

**Comment by i4004** [comment]
I mean just paste here a simple HTML code block where you have a problem, no need to send all project :)

If you are trying to do multiple buttons in one form then you can split it to multiple forms with single button in each form, or change form action dynamically after button was clicked. You are specifying form our you can do it like this: http://stackoverflow.com/questions/16660734/html-form-with-multiple-actions
